const path = require('path');

// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
require('mocha');

describe('1 - it add a new user', function() {
  this.timeout(30000)
  let driver
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('1 - it add a new user', async function() {
    await driver.get("http://localhost/efrei/tests-rendu/src/model/");
    await driver.manage().window().setRect({ width: 725, height: 672 })
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys("marie")
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("espinosa@gmail.com")
    await driver.findElement(By.css("button")).click()
    {
      const elements = await driver.findElements(By.css("li"))
      assert(elements.length)
    }
  })
})
